name: Develop Workflow


on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache bin file
        id: cache-bin
        uses: actions/cache@v2
        with:
          path: ./main
          key: ${{ hashFiles('src/') }}
  
      - uses: actions/setup-go@v2
        if: steps.cache-bin.outputs.cache-hit != 'true'
        with:
          go-version: 1.16

      - name: Cache go module
        if: steps.cache-bin.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        if: steps.cache-bin.outputs.cache-hit != 'true'
        run: go test -v ./...
      
      - name: Build
        if: steps.cache-bin.outputs.cache-hit != 'true'
        run : |
          go build -o bin/ -v ./...
          mv bin/src ./main
