name: Continuous Test


on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: go test -v ./...
